# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('release_date', models.DateField()),
                ('duration', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AlbumWithSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albumId', models.ManyToManyField(to='musicHistoryAPI.Album')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('formed', models.DateField()),
                ('influences', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='ArtistOnAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albumId', models.ManyToManyField(to='musicHistoryAPI.Album')),
                ('artistId', models.ManyToManyField(to='musicHistoryAPI.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('instrument', models.CharField(max_length=55)),
                ('artistId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicHistoryAPI.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('duration', models.TimeField()),
                ('artistId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicHistoryAPI.Artist')),
                ('genreId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicHistoryAPI.Genre')),
            ],
        ),
        migrations.AddField(
            model_name='albumwithsong',
            name='songId',
            field=models.ManyToManyField(to='musicHistoryAPI.Song'),
        ),
        migrations.AddField(
            model_name='album',
            name='artistId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicHistoryAPI.Artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='genreId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicHistoryAPI.Genre'),
        ),
    ]
